name: CI

# This workflow is triggered on pull requests and pushes to the main branch
on:
  pull_request:
  push:
    branches: [main]

# Permissions required for the workflow
permissions:
  contents: read

jobs:
  # Job to scan Ruby code for common Rails security vulnerabilities
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Brakeman for static analysis
        run: bin/brakeman --no-pager

  # Job to scan JavaScript dependencies for security vulnerabilities
  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Importmap audit
        run: bin/importmap audit

  # Job to lint Ruby code for consistent style
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RuboCop for linting
        run: bin/rubocop -f github

  # Job to run tests for the application
  test:
    runs-on: ubuntu-latest

    # Services required for the test job
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      # Redis service is commented out but can be enabled if needed
      # redis:
      #   image: redis
      #   ports:
      #     - 6379:6379
      #   options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in script directory
        run: ls -l script

      - name: Make script executable
        run: chmod +x script/install_dependencies_to_github_actions.sh

      - name: Install system dependencies
        run: script/install_dependencies_to_github_actions.sh

      - name: Validate Chrome and Chromedriver installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          # REDIS_URL: redis://localhost:6379/0
        run: |
          bundle exec rails db:prepare
          bundle exec rails test
          xvfb-run -a bundle exec rails test:system

      - name: Upload screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
